wandb_version: 1

task:
  desc: null
  value: multiomic
seed:
  desc: null
  value: 42
dataset_name:
  desc: null
  value: SCMBench
do_train:
  desc: null
  value: true
load_model:
  desc: null
  value: /ailab/user/liuxinyuan/projects/foundation_models/scGPT/whole_human
freeze:
  desc: null
  value: true
GEP:
  desc: null
  value: true
GEPC:
  desc: null
  value: true
CLS:
  desc: null
  value: false
ESC:
  desc: null
  value: false
DAR:
  desc: null
  value: true
DSBN:
  desc: null
  value: false
mask_ratio:
  desc: null
  value: 0.4
explicit_zero_prob:
  desc: null
  value: false
ecs_thres:
  desc: null
  value: 0
dab_weight:
  desc: null
  value: 1.0
use_batch_labels:
  desc: null
  value: true
use_mod:
  desc: null
  value: true
per_seq_batch_sample:
  desc: null
  value: false
epochs:
  desc: null
  value: 10
input_layer_key:
  desc: null
  value: X_binned
n_bins:
  desc: null
  value: 51
n_hvg:
  desc: null
  value: 1200
n_hvp:
  desc: null
  value: 4000
max_seq_len:
  desc: null
  value: 4001
lr:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 16
layer_size:
  desc: null
  value: 512
nlayers:
  desc: null
  value: 4
nhead:
  desc: null
  value: 8
dropout:
  desc: null
  value: 0.2
schedule_ratio:
  desc: null
  value: 0.95
save_eval_interval:
  desc: null
  value: 5
log_interval:
  desc: null
  value: 100
fast_transformer:
  desc: null
  value: true
pre_norm:
  desc: null
  value: false
amp:
  desc: null
  value: true
pad_token:
  desc: null
  value: <pad>
mask_value:
  desc: null
  value: -1
pad_value:
  desc: null
  value: -2
include_zero_gene:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.7
    framework: huggingface
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1725007272
    t:
      1:
      - 1
      - 5
      - 40
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 40
      - 49
      - 51
      - 53
      - 55
      3:
      - 7
      - 16
      - 23
      - 63
      4: 3.9.19
      5: 0.17.7
      8:
      - 1
      - 6
      13: linux-x86_64
    m:
    - 1: epoch
    - 1: valid/loss
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: test/avg_bio
      6:
      - 3
      7:
      - 2
